require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '15.1'

target 'example' do
  use_frameworks! :linkage => :static
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Hermes
    :hermes_enabled => true,
    # Enables Fabric renderer (New Architecture)
    :fabric_enabled => true
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      # Set this to true to enable the new architecture
      :mac_catalyst_enabled => false
    )
  end
end
